# base go image
FROM golang:1.21.3 as builder

RUN mkdir /app

COPY . /app

WORKDIR /app

RUN CGO_ENABLED=0 go build -o brokerApp ./cmd

RUN chmod +x /app/brokerApp

# build
FROM alpine:latest

RUN mkdir /app

COPY --from=builder /app/brokerApp /app

EXPOSE 8090

CMD [ "/app/brokerApp" ]