version: '3'

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/dockerfile
    restart: always
    ports:
      - "8090:8090"
    deploy:
     mode: replicated
     replicas: 1

  quote-service:
    build:
      context: ./../quote-service
      dockerfile: ./../quote-service/dockerfile
    restart: always
    ports:
      - "8091:8091"
    deploy:
      mode: replicated
      replicas: 1